version: '3.1'
services:
  server:
    build: ./stats/server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me-stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

#  ewm-service:
#    ports:
#      - "8080:8080"
#
#  ewm-db:
#    image: postgres:14-alpine
