version: '3.1'
services:
  server:
    build: ./stats/server
    image: server-image
    container_name: server-container
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me-stats

  stats-db:
    image: postgres:14-alpine
    container_name: postgres-stats-db-container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=explore_with_me-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: ./main
    image: main-image
    container_name: main-container
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - server
    environment:
    - CLIENT_URL=http://stats-server:9090
    - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/explore_with_me-main

  ewm-db:
    image: postgres:14-alpine
    container_name: main-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=explore_with_me-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
